### PR TITLE
feat: allow new doctrine dbal and orm versions

### PR DESCRIPTION
**Pull request by shakaran**

### CODE REVIEW

**Comment by SimonMellerin** [comment]
Hi thanks for your PR.

This update is not insignificant and will require us to perform a few tests before we can mark this version as compatible with the DbToolsBundle. 

I will close this one for now as we are not yet ready.

On your side, did you tested the DbToolsBundle on a living project with Doctrine and DBAL 3 already ? 

Cheers

**Comment by shakaran** [comment]
Could we at least keep a dev branch or unstable official for test all this with new releases? I am fixing all the deprecations notices with Symfony 7.0 and try to support this in all codebases of my clients with PHP 8.3

**Comment by shakaran** [comment]
> or the suggestion, I'll pre

Thanks for reconsidering. And sorry if I was a bit rude in the other reply or PR (if you read it later my other response) (I am working quick with a lot pressure in my shoulders for keep all this updated in a lot projects)

**Comment by pounard** [comment]
I opened https://github.com/makinacorpus/DbToolsBundle/issues/140 and will work on a new PR for this, thanks for reporting, I'm closing this PR.

**Pull request closed without merging**
